name: shell command

on:
  push:
    branches:
      - master
env:
  var1: this var is hard coded

jobs:
  run-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: inside directory
        run: ls -a
      - name: echo a string
        run: echo "hello Amin"
      - name: multi line run
        run: |
          node -v
          npm -v
      - name: python script
        run: |
          import platform
          print (platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell"]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
  run-ubuntu:
    runs-on: ubuntu-latest
    needs: ["run-windows-command"]
    env:
      var2: ${{ secrets.FOO_TOKEN1 }}
    steps:
      - uses: actions/checkout@master
      - name: environmrnt variables
        run: sh ./shell-commands.sh
      - name: java version before installation
        run: |
          echo "var1: ${var1}" &&
          echo "var2: ${var2}" &&
          echo java version before installing java 8 &&
          java -version
      - name: Installing Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: what is installed
        run: |
          echo what is inside Directory &&
          ls -a &&
          echo java version after installing java 8 &&
          java -version
      